spring:
  application:
    name: api
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    deferDatasourceInitialization: true
    showSql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
